name: CI/CD for Hello World

on:
  workflow_dispatch:
  push:
    branches:
      - development # For Dev environment
      - release # For QA environment
      - main # For Production environment

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Applying Exec Permissions
        run: |
          chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test

  scan:
    name: Security and Quality Scan
    runs-on: ubuntu-latest
    needs: build
    steps:      
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@v2
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          severity-threshold: high
          json: true
        continue-on-error: true

      - name: Convert Snyk JSON to SARIF
        uses: garethr/snyk-to-sarif@master

      - name: Upload SARIF file to GitHub Security
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: scan
    if: github.ref == 'refs/heads/development'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push Docker Image to Docker Hub
        run: |
          docker tag hello-world:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/hello-world:dev
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-world:dev
      - name: Deploy to Dev Environment
        run: echo "Deploying to Dev environment..."

  deploy-qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    needs: scan
    if: github.ref == 'refs/heads/release'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push Docker Image to Docker Hub
        run: |
          docker tag hello-world:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/hello-world:qa
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-world:qa
      - name: Deploy to QA Environment
        run: echo "Deploying to QA environment..."

  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: scan
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push Docker Image to Docker Hub
        run: |
          docker tag hello-world:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/hello-world:prod
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-world:prod
      - name: Deploy to Production Environment
        run: echo "Deploying to Production environment..."
