name: CI/CD for Hello World

on:
  workflow_dispatch:
  push:
    branches:
      - development # For Dev environment
      - release # For QA environment
      - main # For Production environment

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js (example for a Node.js app)
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test
      - name: Build Docker Image
        run: docker build -t hello-world:${{ github.sha }} .

  scan:
    name: Security and Quality Scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Snyk Security Scan
        uses: snyk/actions/node@v2
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Quality Gate with SonarQube
        run: |
          sonar-scanner \
            -Dsonar.projectKey=hello-world \
            -Dsonar.organization=my-org \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: scan
    if: github.ref == 'refs/heads/development'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push Docker Image to Docker Hub
        run: |
          docker tag hello-world:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/hello-world:dev
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-world:dev
      - name: Deploy to Dev Environment
        run: echo "Deploying to Dev environment..."

  deploy-qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    needs: scan
    if: github.ref == 'refs/heads/release'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push Docker Image to Docker Hub
        run: |
          docker tag hello-world:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/hello-world:qa
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-world:qa
      - name: Deploy to QA Environment
        run: echo "Deploying to QA environment..."

  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: scan
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push Docker Image to Docker Hub
        run: |
          docker tag hello-world:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/hello-world:prod
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-world:prod
      - name: Deploy to Production Environment
        run: echo "Deploying to Production environment..."
